### ISSUE TITLE
Implement package signing

### ISSUE THREAD

**Issue by spolack** [Freifunk-Spalter/repo_builder#1]
In order to make opkg eat the resulting repository, the Package files have to get signed.

**Comment by PolynomialDivision** [comment]
Currently, I'm signing with
```#!/bin/bash

package_list=$(find -name "Packages")
for list in $package_list; do
	echo $list
	./usign -S -m $list -s key-build
done
```

**Comment by spolack** [comment]
Would you mind implementing it into the build_feed script? maybe optional, let the keyfile path be passed via parameter.

**Comment by Akira25** [comment]
@PolynomialDivision @spolack was there any progress on this issue? As the buildbot can build packagefeed automatically now, I'm really keen on having this feature included. :)

**Comment by PolynomialDivision** [comment]
@Akira25 I can have a look again tomorrow. But where should we put the private key?

**Comment by PolynomialDivision** [comment]
I made some draft: https://github.com/Freifunk-Spalter/repo_builder/pull/5

But we need to install usign for that on all build bots. And we have to create a signing key.

**Comment by Akira25** [comment]
Installing usign is no problem. :) What do propose on the key?

**Comment by PolynomialDivision** [comment]
> Installing usign is no problem. :) What do propose on the key?

Who has the key, also has the power. xD I really have no clue. It is definitely a attack vector, which we should handle carefully.

**Comment by Akira25** [comment]
What about building automatically, but signing manually?

**Comment by PolynomialDivision** [comment]
I would be happy, to have continious new builds directly available at the opkg feed. :)

**Comment by Akira25** [comment]
This issue should be solved by now. On buildbot-master, the packages get signed by a script similar to this:

> ```shell
> #!/bin/bash
> 
> package_list=$(find -name "Packages")
> for list in $package_list; do
> 	echo $list
> 	./usign -S -m $list -s key-build
> done
> ```

http://buildbot.berlin.freifunk.net/buildbot/feed/new/
