### ISSUE TITLE
Request for more ready-made feeds

### ISSUE THREAD

**Issue by pmelange** [Freifunk-Spalter/repo_builder#8]
In order to be able to support more simultaneous prototyping environs, I think it would be beneficial for us to automatically build feeds upon merges to the repo for the "openwrt-19.07", "openwrt-21.02" and "master" branches.  

I recommend that the feeds be placed into:
http://buildbot.berlin.freifunk.net/buildbot/feed/19.07-SNAPSHOT
http://buildbot.berlin.freifunk.net/buildbot/feed/21.02-SNAPSHOT
http://buildbot.berlin.freifunk.net/buildbot/feed/snapshots

When we make beta releases, release candidates, and releases, I recommend:
http://buildbot.berlin.freifunk.net/buildbot/feed/$FREIFUNK_RELEASE  (1.1.0-beta5, 1.1.0-rc1, 1.1.0)

Can the repo_builder be changed to reflect these changes?  @Akira25 should I make an extra issue at buildbot to get the automatic builds integrated?

**Comment by pmelange** [comment]
Actually, I don't think I like the idea of having these feed directories:


> http://buildbot.berlin.freifunk.net/buildbot/feed/19.07-SNAPSHOT
> http://buildbot.berlin.freifunk.net/buildbot/feed/21.02-SNAPSHOT
> http://buildbot.berlin.freifunk.net/buildbot/feed/snapshots

But instead put everything in $FREIFUNK_RELEASE.  The value of FREIFUNK_RELEASE on the three branches  "openwrt-19.07", "openwrt-21.02" and "master" are "1.1.1-snapshot", "1.2.0-snapshot" and "snapshot" (once PR https://github.com/Freifunk-Spalter/packages/pull/156 gets merged).

So, as a review:
http://buildbot.berlin.freifunk.net/buildbot/feed/snapshot
http://buildbot.berlin.freifunk.net/buildbot/feed/1.1.1-snapshot
http://buildbot.berlin.freifunk.net/buildbot/feed/1.1.1-betaX
http://buildbot.berlin.freifunk.net/buildbot/feed/1.1.1-rcY
http://buildbot.berlin.freifunk.net/buildbot/feed/1.1.1
http://buildbot.berlin.freifunk.net/buildbot/feed/1.2.0-snapshot
http://buildbot.berlin.freifunk.net/buildbot/feed/1.2.0-betaX
http://buildbot.berlin.freifunk.net/buildbot/feed/1.2.0-rcY
http://buildbot.berlin.freifunk.net/buildbot/feed/1.2.0

**Comment by Akira25** [comment]
> But instead put everything in $FREIFUNK_RELEASE. The value of FREIFUNK_RELEASE on the three branches "openwrt-19.07", "openwrt-21.02" and "master" are "1.1.1-snapshot", "1.2.0-snapshot" and "snapshot" (once PR [Freifunk-Spalter/packages#156](https://github.com/Freifunk-Spalter/packages/pull/156) gets merged).
> 
> So, as a review:
> http://buildbot.berlin.freifunk.net/buildbot/feed/snapshot
> http://buildbot.berlin.freifunk.net/buildbot/feed/1.1.1-snapshot
> http://buildbot.berlin.freifunk.net/buildbot/feed/1.1.1-betaX
> http://buildbot.berlin.freifunk.net/buildbot/feed/1.1.1-rcY
> http://buildbot.berlin.freifunk.net/buildbot/feed/1.1.1
> http://buildbot.berlin.freifunk.net/buildbot/feed/1.2.0-snapshot
> http://buildbot.berlin.freifunk.net/buildbot/feed/1.2.0-betaX
> http://buildbot.berlin.freifunk.net/buildbot/feed/1.2.0-rcY
> http://buildbot.berlin.freifunk.net/buildbot/feed/1.2.0

I like that idea. Currently I'm, really busy with other stuff, so it might take a while until I can have a look on that.

**Comment by Akira25** [comment]
@pmelange That should have been implemented by https://github.com/Freifunk-Spalter/buildbot/commit/46b9334c0b7651a7d229a3b28b7c2aaf8c013110. A succesful build was done [here](https://buildbot.berlin.freifunk.net/#/builders/52/builds/33).

**Comment by pmelange** [comment]
Very nice.  I see snapshot and 1.1.1-snapshot.  could we also get 1.1.0 in there?  Maybe it's just possible to copy the openwrt-19.07 directory over there.

**Comment by Akira25** [comment]
> Very nice. I see snapshot and 1.1.1-snapshot. could we also get 1.1.0 in there? Maybe it's just possible to copy the openwrt-19.07 directory over there.

That are just my test-builds from the feed branch. The new feeds will appear as soon, as we push something on the `openwrt-*`-branches in the packages repo.
